erDiagram
    Cliente {
        int id_cliente PK
        varchar(100) nome
        varchar(11) telefone
        varchar(14) cpf
    }

    Betoneira {
        int id_betoneira PK
        varchar(100) modelo
        boolean status "True para Disponível, False para Alugado"
        float valor "Preço da diária"
    }

    Aluguel{
        int id_aluguel PK
        int id_cliente FK
        int id_betoneira FK
        date data_retirada "Data da retirada"
        date data_devolucao "Data de devolução"
    }

    -- Adicionando as linhas de relacionamento --
    Cliente ||--o{ Aluguel : "faz"
    Betoneira ||--o{ Aluguel : "é objeto de"